hemolegal/core/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.contrib import admin
from . import views

app_name = 'core'

urlpatterns = [
	path('', views.Home.as_view(),name='home'),
	path('cadastro_doador/', views.CadastroDoador.as_view(),name='cadastro_doador'),
	path('doadores/', views.ListarDoadores.as_view(),name='doadores'),
    path('detalhe_doador/<int:doador_id>', views.DetalheDoador.as_view(), name='detalhe_doador'),
    path('detalhe_doacao/<int:doacao_id>', views.DetalheDoacao.as_view(), name='detalhe_doacao'),
]

hemolegal/hemolegal/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include('core.urls', namespace='core') ),
]

hemolegal/core/models.py
from django.db import models
from datetime import datetime

TIPO_SANGUE = (
		('ap', 'A+'),
		('an', 'A-'),
		('bp', 'B+'),
		('bn', 'B-'),
		('abp', 'AB+'),
		('abn', 'AB-'),
		('op', 'O+'),
		('on', 'O-'),
)

class Endereco(models.Model):
	logradouro = models.CharField(max_length = 50, verbose_name = 'logradouro')
	numero = models.IntegerField()
	bairro = models.CharField(max_length = 50, verbose_name = 'bairro')
	estado = models.CharField(max_length = 50, verbose_name = 'estado')
	cidade = models.CharField(max_length = 50, verbose_name = 'cidade')

class Hospital(models.Model):
	nome = models.CharField(max_length = 30, verbose_name = 'nome')
	telefone = models.CharField(max_length = 14, verbose_name = 'telefone')
	endereco = models.OneToOneField('Endereco', on_delete = models.CASCADE, related_name = 'hospital_endereco')


class Hemocentro(models.Model):
	nome = models.CharField(max_length = 30, verbose_name = 'nome')
	telefone = models.CharField(max_length = 14, verbose_name = 'telefone')
	estoque_sanguineo = models.ForeignKey('Estoque', on_delete = models.CASCADE, related_name = 'meu_estoque')
	endereco = models.OneToOneField('Endereco', on_delete = models.CASCADE, related_name = 'hemocentro_endereco')

class Doador(models.Model):
	SEXO = (
		('F', u'Feminino'),
		('M', u'Masculino'),
	)

	nome = models.CharField(max_length = 30, verbose_name = 'nome')
	cpf = models.CharField(max_length = 11, verbose_name = 'cpf')
	sexo = models.CharField(max_length = 10, choices = SEXO)
	telefone = models.CharField(max_length = 14, verbose_name = 'telefone')
	dt_nascimento = models.DateField(auto_now = False)
	endereco = models.ForeignKey('Endereco', on_delete = models.CASCADE, related_name = 'doador_endereco')
	sangue = models.CharField(max_length = 3, choices = TIPO_SANGUE)

class Estoque(models.Model):
	tipo_sangue = models.CharField(max_length = 3, choices = TIPO_SANGUE)
	quant_bolsas = models.IntegerField()

	def checar_estoque():
		"""checa o número de bolsas e caso o estoque esteja baixo, nao permitir transações. Quantias ideais:
		considerar as outras como 100
		O+ >=  250 bolsas
		O- >= 20 bolsas
		AB- >= 4"""


class Doacao(models.Model):
	doador = models.ForeignKey('Doador', on_delete = models.CASCADE, related_name = 'doacoes_realizadas') 
	hemocentro = models.ForeignKey('Hemocentro', on_delete = models.CASCADE, related_name = 'doacoes_recebidas')
	data_doacao =  models.DateField(auto_now = True)
	quant_bolsas = models.IntegerField()
	direcionada = models.BooleanField()
	paciente = models.CharField(max_length = 30, verbose_name = 'paciente')
	hospital = models.ForeignKey('Hospital', on_delete = models.CASCADE, related_name = 'doacoes_direcionadas')

	def checar_idade_doador(self):
		#CHECAR SE O DOADOR É MAIOR DE IDADE, SE NAO FOR DEVE EXIGIR DOCUMENTAÇÃO DE AUTORIZAÇÃO (CADASTRAR UM CODIGO DA AUTORIZACAO).
		if (datetime.now() - Doacao.objects.filter(doador = self.doador).filter(dt_nascimento)).years > 18:
			raise ValidationError('Doador necessita da autorização dos responsáveis!!')

	def chegar_intervalo_doacao(self):
		""" CHECAR O INTERVALO DA ULTIMA DOAÇÃO P/ DOAÇÃO ATUAL:
			HOMEM: 2 MESES(60 DIAS)
			MULHERES: 3 MESES(90 DIAS)"""
			


class Transacao(models.Model):
	tipo_sangue = models.CharField(max_length = 3, choices = TIPO_SANGUE)
	emissor = models.ForeignKey('Hemocentro', on_delete = models.CASCADE, related_name = 'repasses')
	receptor = models.ForeignKey('Hospital', on_delete = models.CASCADE, related_name = 'recebidos')
	data_transacao = models.DateField(auto_now = True)
	quant_bolsas = models.IntegerField()


		

hemolegal/user/models.py
from django.db import models


		
	
		

hemolegal/core/forms.py
from django import forms
from .models import Doador, Endereco

class FormDoador(forms.ModelForm):
	class Meta:
		model = Doador		
		fields = '__all__'
		exclude = ['endereco']

class FormEndereco(forms.ModelForm):
	class Meta:
		model = Endereco		
		fields = '__all__'

hemolegal/core/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import Doador, Doacao, Endereco
from .forms import FormDoador, FormEndereco

class Home(View):
	"""EXIBIR TOP 5 DOADORES E CAMPANHAS QUE ESTEJAM EM ANDAMENTO. ALGO COMO NOTÍCIAS OU NOTAS SERIA INTERESSANTE EXIBIR TAMBÉM."""
	
	
	def get(self, request):
		doadores = Doador.objects.all()
		quant = len(doadores)
		return render(request, "core/home.html", {'quant':quant})


class CadastroDoador(View):

	def get(self, request):
		form = FormDoador()
		endereco = FormEndereco()
		return render(request, "core/cadastro_doador.html", {'form':form, 'endereco': endereco})

	def post(self, request):		
		
		endereco = Endereco.objects.create(		
				logradouro = request.POST['logradouro'],
				numero = request.POST['numero'],
				cidade = request.POST['cidade'],
				bairro = request.POST['bairro'],
				estado = request.POST['estado']
			)

		doador = Doador(nome = request.POST['nome'],
			   dt_nascimento = request.POST['nascimento'],
			   cpf = request.POST['cpf'],
			   telefone = request.POST['telefone'],
			   sexo = request.POST['sexo'],
			   sangue = request.POST['tipo_sangue']
			)

		doador.endereco = endereco
		doador.save()	

		return redirect('core:doadores')

class ListarDoadores(View):
	def get(self, request):
		doadores = Doador.objects.all()
		quant = len(doadores)

		return render(request, "core/doadores.html", {'doadores':doadores, 'quant':quant})


class DetalheDoador(View):
	def get(self, request, *args, **kwargs):
		doador_id = self.kwargs['doador_id']
		doador = Doador.objects.get(pk = doador_id)

		return render(request, "core/detalhe_doador.html", {'doador': doador})

class DetalheDoacao(View):
	def get(self, request, *args, **kwargs):
		doacao_id = self.kwargs['doacao_id']
		doacao = Doacao.objects.get(pk = doacao_id)

		return render(request, "core/detalhe_doacao.html", {'doacao': doacao})

hemolegal/user/views.py
from django.shortcuts import render

# Create your views here.

hemolegal/core/templates/core/base.html
{% load static %}
{% load bootstrap %}


<!DOCTYPE html>
<html lang="pt-br">



<head>
	<title>{% block title %}{% endblock %}</title>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
	<link rel="stylesheet" href="{% static "css/style.css" %}" >
	
</head>

<body>
	<div class="container">
		<header class="row">
			<ul class="nav nav-tabs" id="myTab" role="tablist">
		 		<li class="nav-item"><a class="nav-link active" id="home-tab" data-toggle="tab" href="{% url 'core:home' %}" role="tab" aria-controls="home" aria-selected="true">Home</a>
		  		</li>
		  		<li class="nav-item"><a class="nav-link" id="doadores-tab" data-toggle="tab" href="{% url 'core:doadores' %}" role="tab" aria-controls="doadores" aria-selected="false">Doadores</a>
		  		</li>
		  		<li class="nav-item"><a class="nav-link" id="campanhas-tab" data-toggle="tab" href="#campanhas" role="tab" aria-controls="campanhas" aria-selected="false">Campanhas</a>
		  		</li>
			</ul>
		</header>	

		<main class="row">

			{% block content %}

			{% endblock %}
			
		</main>

		<footer class="row">
			Todos os Direitos Reservados - HemoLegal - 2018
		</footer>
	</div>

</html>

hemolegal/core/templates/core/cadastro_doador.html
{% extends './base.html' %}
{% load bootstrap %}
{% block content %}
    
    <h3>Novo Doador</h3>
    <form method="POST" action='/cadastro_doador/'>
        {% csrf_token %}
        <div class="form-row">
            <div class="col-md-8 mb-6">
                  <label for="nome">Nome</label>
                  <input type="text" class="form-control" name="nome" id="nome" placeholder="Name" required>
            </div>

            <div class="col-md-4 mb-3">
                <label for="nascimento">Data de nascimento</label>
                <input type="date" class="form-control" id="nascimento" name="nascimento" placeholder="nascimento" required>
            </div>
        </div>

        <div class="form-row">
            <div class="col-md-4 mb-3">
                  <label for="cpf">CPF</label>
                  <input type="text" class="form-control" id="cpf" name="cpf" placeholder="CPF" required>
            </div>

            <div class="col-md-4 mb-3">
                <label for="telefone">Telefone</label>
                <input type="text" class="form-control" id="telefone"  name="telefone" placeholder="Telefone" required>
            </div>

            <div class="col-md-2 mb-3">
                <label for="sexo">Sexo</label>
                <select name='sexo' class="form-control">
                    <option>--</option>
                    <option>Feminino</option>
                    <option>Masculino</option>
                </select>
            </div>

            <div class="col-md-2 mb-3">
                <label for="tipo_sangue">Tipo Sanguíneo</label>
                <select name='tipo_sangue' class="form-control">
                    <option>--</option>
                    <option>A+</option>
                    <option>A-</option>
                    <option>B+</option>
                    <option>B-</option>
                    <option>AB+</option>
                    <option>AB-</option>
                    <option>O+</option>
                    <option>O-</option>
                </select>
            </div>
        </div>

        <div class="form-row">
            <div class="col-md-9 mb-6">
                  <label for="logradouro">Logradouro</label>    
                  <input type="text" class="form-control" name="logradouro" id="logradouro" placeholder="Logradouro" required>
            </div>

            <div class="col-md-3 mb-3">
                <label for="numero">Numero</label>
                <input type="text" class="form-control" name="numero" id="numero" placeholder="Numero" required>
            </div>
        </div>

        <div class="form-row">
            <div class="col-md-4 mb-3">
                  <label for="bairro">Bairro</label>
                  <input type="text" class="form-control" name="bairro" id="bairro" placeholder="Bairro" required>
            </div>

            <div class="col-md-4 mb-3">
                <label for="cidade">Cidade</label>
                <input type="text" class="form-control" name="cidade" id="cidade" placeholder="Cidade" required>
            </div>

            <div class="col-md-4 mb-3">
                <label for="estado">Estado</label>
                <input type="text" class="form-control" id="estado" name="estado" placeholder="Estado" required>
            </div>
        </div>

        <button type="submit" name="action" class="btn btn-danger">Cadastrar</button>
             
    </form>

    
    
    {% if form.subject.errors %}
    <ol>
    {% for error in form.subject.errors %}
        <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
    </ol>
	{% endif %}
{% endblock %}

hemolegal/core/templates/core/detalhe_doacao.html
{% extends './base.html' %}
{% load static %}
{% load bootstrap %}

{% block title %}Doacao {{doacao.id}}{% endblock %}
{% block content %}	

		<div class="panel panel-danger">
			<div class="panel-heading">
				<p><h3>Doacão de nº {{doacao.id}}</h3></p>
				<p><h4>Realizada em {{doacao.data_doacao}}</h4></p>
			</div>

			<div class="panel-body">
				<p>Hemocentro: {{doacao.hemocentro.nome}}</p>
				<p><a href="{% url 'core:detalhe_doador' doador_id=doacao.doador.pk %}">Doador: {{doacao.doador.nome}}</a></p>
				<p>Sexo: {{doacao.doador.sexo}}</p>
				<p>Tipo sanguíneo: {{doacao.doador.sangue}}</p>
		
				{% if doacao.direcionada %}			
					<strong>Direcionada:</strong> {{doacao.paciente}} - {{doacao.hospital.nome}}
				{% endif %}
			</div>
	    </div>


{% endblock %}

hemolegal/core/templates/core/detalhe_doador.html
{% extends './base.html' %}
{% load static %}
{% load bootstrap %}
{% block content %}	
	
	<div class="panel-group">
		<div class="panel panel-danger">
			<div class="panel-heading">
				<h3>{{doador.nome}} <span class="glyphicon glyphicon-tint"></span>{{doador.sangue}}</h3>
			</div>

			<div class="panel-body">
				<p>Contato: {{doador.telefone}}</p>
				<p>Sexo: {{doador.sexo}}</p>
				<p>Data de nascimento: {{doador.dt_nascimento}}</p>

			</div>
	    </div>
	</div>
	
{% endblock %}

hemolegal/core/templates/core/doadores.html
{% extends './base.html' %}
{% load bootstrap %}
{% block content %}

<h2>Doadores</h2>
<h3>Hoje somos {{quant}}</h3>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Nº</th>
      <th scope="col">Nome</th>
      <th scope="col">CPF</th>
      <th scope="col">Telefone</th>
      <th scope="col">Sangue</th>
      <th scope="col">Detalhes</th>
    </tr>
  </thead>
  <tbody>
  	{% for doador in doadores %}
    <tr>
      
        <th scope="row">{{doador.id}}</th>
        <td>{{doador.nome}}</td>
        <td>{{doador.cpf}}</td>
        <td>{{doador.telefone}}</td>
        <td>{{doador.sangue}}</td>
        <td><a href="{% url 'core:detalhe_doador' doador_id=doador.pk %}">DETALHAR</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

hemolegal/core/templates/core/home.html
{% extends './base.html' %}
{% load bootstrap %}

{% block title %}Página inicial{% endblock %}
{% block content %}

	
	<div class="row">
		<h1>HemoLegal ;)</h1>
		<div class="col-md-7">
			<div class="row" id="lateral_login">
				<div class="col-sm-6" >
					<div class="card">
						<div class="card-body">
							<h4 class="card-title">Doadores</h4>
							<p class="card-text">Somos {{quant}}, cadastre-se e faça parte desse time!</p>
							<a href="{% url 'core:cadastro_doador' %}" class="btn btn-danger">Cadastre-se</a>
						</div>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="card">
						<div class="card-body">
							<h4 class="card-title">Doações</h4>
							<p class="card-text">Uma doação de sangue pode salvar até quatro vidas.</p>
							<a href="#" class="btn btn-danger">Doe</a>	
						</div>
					</div>
				</div>
			</div>
		</div>
		
		<div class="col-md-5" id="login">
			<h4>Login</h4>
			<form class="px-4 py-3" method="POST">
				<form>
					<div class="form-group">
						<label for="exampleInputEmail1">Usuário</label>
						<input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Usuario">
					</div>
					<div class="form-group">
						<label for="exampleInputPassword1">Password</label>
						<input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
					</div>

					<div class="dropdown-divider">
						<button type="submit" class="btn btn-danger btn-block">Entrar</button>	
						<br><p>Novo por aqui? <a class="dropdown-item" href="#">Cadastre-se</a></p>
					</div>
				</form>
			</form>
		</div>
	</div>

{% endblock %}